# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

stages:
################## Step SAST ##################
- stage: SAST
  jobs:
  - job: SAST
    displayName: 'Static Analysis and Security Testing'
    steps:
    - task: SonarCloudPrepare@1
      displayName: 'Preparacion Sonar Cloud'
      inputs:
        SonarCloud: 'Sonar'
        organization: 'adrianvirus2022'
        scannerMode: 'Other'
        extraProperties: |
            # Additional properties that will be passed to the scanner,
            # Put one key=value per line, example:
            # sonar.exclusions=**/*.bin
            sonar.projectKey=adrianvirus2022
            sonar.projectName=adrianvirus2022
    - task: Maven@4
      displayName: 'Analisis Codigo - Maven'
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
        checkStyleRunAnalysis: true
        pmdRunAnalysis: true
        findBugsRunAnalysis: true

    - task: sonarcloud-buildbreaker@2
      displayName: 'The Breaker'
      inputs:
        SonarCloud: 'Sonar'
        organization: 'adrianvirus2022'
    - task: SonarCloudPublish@1
      displayName: 'Publicacion de reporte SonarCloud'
      inputs:
        pollingTimeoutSec: '300'
    
################## Step SCA ##################
- stage: SCA
  jobs:
  - job: SCA
    displayName: 'SCA'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '*/surefire-reports/TEST-.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: dependency-check-build-task@6
      inputs:
        projectName: 'spring-boot-kubernetes'
        scanPath: '$(Build.ArtifactStagingDirectory)'
        format: 'HTML'


