# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

stages:
- stage: SAST
  jobs:
  - job: SAST
    displayName: 'Oscar chupalo'
    steps:
    - task: SonarCloudPrepare@1
      displayName: 'SonarCloud Prepare'
      inputs:
        SonarCloud: 'Sonar'
        organization: 'adrianvirus2022'
        projectKey: 'spring-boot-kubernetes'
        projectName: 'adrianvirus2022'

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '*/surefire-reports/TEST-.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        sonarQubeRunAnalysis: true

    # - task: Maven@4
    #   inputs:
    #     mavenPomFile: 'pom.xml'
    #     publishJUnitResults: false
    #     javaHomeOption: 'JDKVersion'
    #     mavenVersionOption: 'Default'
    #     mavenAuthenticateFeed: false
    #     effectivePomSkip: false
    #     sonarQubeRunAnalysis: true
    #     sqMavenPluginVersionChoice: 'latest'
    #   env:
    #     SONAR_TOKEN: $(SONAR_TOKEN)

    - task: SonarCloudAnalyze@1
      displayName: 'SonarCloud Analyzer'

    - task: SonarCloudPublish@1
      displayName: 'SonarCloud Publish'
      inputs:
        pollingTimeoutSec: '300'